services:
  openproject:
    image: openproject/openproject:16
    container_name: openproject-app
    ports:
      - "8080:80"
    environment:
      OPENPROJECT_SECRET_KEY_BASE: "tu-clave-secreta-aqui-cambiala-por-una-segura"
      OPENPROJECT_HOST__NAME: localhost:8080
      OPENPROJECT_HTTPS: false
      OPENPROJECT_DEFAULT__LANGUAGE: es
    volumes:
      - openproject-data:/var/openproject/pgdata
      - openproject-assets:/var/openproject/assets
    restart: unless-stopped

volumes:
  openproject-data:
  openproject-assets:
