version: '3.8'

services:
  taiga-db:
    image: postgres:13
    container_name: taiga-postgres
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga123
    volumes:
      - taiga-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  taiga-redis:
    image: redis:6-alpine
    container_name: taiga-redis
    restart: unless-stopped

  taiga-back:
    image: taigaio/taiga-back:latest
    container_name: taiga-backend
    depends_on:
      - taiga-db
      - taiga-redis
    environment:
      TAIGA_DB_HOST: taiga-db
      TAIGA_DB_NAME: taiga
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASS: taiga123
      TAIGA_REDIS_HOST: taiga-redis
      TAIGA_SECRET_KEY: "your-secret-key-here"
      TAIGA_SITES_SCHEME: http
      TAIGA_SITES_DOMAIN: localhost:9001
    volumes:
      - taiga-back-media:/taiga-back/media
      - taiga-back-static:/taiga-back/static
    restart: unless-stopped

  taiga-front:
    image: taigaio/taiga-front:latest
    container_name: taiga-frontend
    depends_on:
      - taiga-back
    environment:
      TAIGA_API_URL: http://taiga-back:8001/api/v1/
      TAIGA_EVENTS_URL: http://taiga-back:8001/events/
    ports:
      - "9001:80"
    restart: unless-stopped

volumes:
  taiga-postgres-data:
  taiga-back-media:
  taiga-back-static:
