version: '3.8'

services:
  taiga:
    image: taigaio/taiga:latest
    container_name: taiga-app
    ports:
      - "9001:80"
    environment:
      TAIGA_SCHEME: http
      TAIGA_DOMAIN: localhost:9001
      SUBPATH: ""
      WEBSOCKETS_SCHEME: ws
      SECRET_KEY: "taiga-secret-key-cambiala-por-una-segura"
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
      POSTGRES_DB: taiga
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      RABBITMQ_VHOST: taiga
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      EMAIL_BACKEND: console
      ATTACHMENTS_MAX_AGE: 360
      ENABLE_TELEMETRY: False
    volumes:
      - taiga-data:/var/lib/taiga
    restart: unless-stopped

volumes:
  taiga-data:
