services:
  taiga:
    image: taigaio/taiga-back:latest
    container_name: taiga-backend
    ports:
      - "9001:8001"
    environment:
      TAIGA_DB_HOST: db
      TAIGA_DB_NAME: taiga
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASS: taiga123
      TAIGA_SECRET_KEY: "taiga-secret-key-cambiala-por-una-segura"
      TAIGA_SITES_SCHEME: http
      TAIGA_SITES_DOMAIN: localhost:9001
      PUBLIC_REGISTER_ENABLED: "True"
    volumes:
      - taiga-back-media:/taiga-back/media
      - taiga-back-static:/taiga-back/static
    depends_on:
      - db
    restart: unless-stopped

  taiga-front:
    image: taigaio/taiga-front:latest
    container_name: taiga-frontend
    ports:
      - "9002:80"
    environment:
      TAIGA_API_URL: http://localhost:9001/api/v1/
      TAIGA_EVENTS_URL: http://localhost:9001/events/
      PUBLIC_REGISTER_ENABLED: "true"
    depends_on:
      - taiga
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: taiga-postgres
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga123
    volumes:
      - taiga-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  taiga-back-media:
  taiga-back-static:
  taiga-postgres-data:
